export const INDIAN_LOCATION_DATA = {
  Kerala: {
    Kottayam: [
      'Pala',
      'Kottayam Town',
      'Changanassery',
      'Kanjirappally',
      'Vaikom',
      'Erattupetta',
      'Ettumanoor',
      'Puthuppally',
      'Pamapady',
      'Kaduthuruthy',
      'Kuravilangad',
      'Mundakayam',
      'Ponkunnam',
      'Ramapuram',
      'Kidangoor',
      'Teekoy',
      'Manarcad',
      'Ayarkunnam',
      'Athirampuzha',
      'Kudamaloor',
      'Kumarakom',
      'Chingavanam',
      'Karukachal',
      'Kooropada',
      'Entire District',
    ],
    'Ernakulam (Kochi)': [
      'Kochi City',
      'Aluva',
      'Edappally',
      'Kaloor',
      'Fort Kochi',
      'Kakkanad',
      'Tripunithura',
      'Angamaly',
      'Perumbavoor',
      'Muvattupuzha',
      'Kothamangalam',
      'North Paravur',
      'Kalamassery',
      'Piravom',
      'Vyttila',
      'Mattancherry',
      'Palarivattom',
      'Maradu',
      'Cherai',
      'Entire District',
    ],
    Thiruvananthapuram: [
      'Trivandrum City',
      'Kazhakkoottam',
      'Neyyattinkara',
      'Attingal',
      'Varkala',
      'Kowdiar',
      'Nedumangad',
      'Kattakada',
      'Vizhinjam',
      'Nemom',
      'Sreekaryam',
      'Pattam',
      'Palayam',
      'Thampanoor',
      'Entire District',
    ],
    Kozhikode: [
      'Calicut City',
      'Vadakara',
      'Koyilandy',
      'Feroke',
      'Ramanattukara',
      'Mavoor',
      'Mukkam',
      'Balussery',
      'Koduvally',
      'Thamarassery',
      'Beypore',
      'Kunnamangalam',
      'Elathur',
      'Entire District',
    ],
    Thrissur: [
      'Thrissur Town',
      'Chalakudy',
      'Guruvayur',
      'Irinjalakuda',
      'Kunnamkulam',
      'Kodungallur',
      'Ollur',
      'Wadakkanchery',
      'Chavakkad',
      'Triprayar',
      'Entire District',
    ],
    Palakkad: [
      'Palakkad Town',
      'Ottapalam',
      'Shoranur',
      'Chittur',
      'Mannarkkad',
      'Pattambi',
      'Alathur',
      'Cherpulassery',
      'Kanjikode',
      'Walayar',
      'Entire District',
    ],
    Alappuzha: [
      'Alappuzha Town',
      'Cherthala',
      'Kayamkulam',
      'Mavelikara',
      'Haripad',
      'Ambalappuzha',
      'Chengannur',
      'Kuthiathode',
      'Kuttanad',
      'Aroor',
      'Entire District',
    ],
    Kannur: [
      'Kannur Town',
      'Thalassery',
      'Payyanur',
      'Mattannur',
      'Iritty',
      'Taliparamba',
      'Kuthuparamba',
      'Chala',
      'Entire District',
    ],
    Kollam: [
      'Kollam City',
      'Karunagappally',
      'Punalur',
      'Paravur',
      'Kottarakkara',
      'Pathanapuram',
      'Chathannoor',
      'Anchal',
      'Entire District',
    ],
    Malappuram: [
      'Malappuram Town',
      'Manjeri',
      'Tirur',
      'Perinthalmanna',
      'Ponnani',
      'Kondotty',
      'Nilambur',
      'Kottakkal',
      'Valanchery',
      'Edapal',
      'Entire District',
    ],
    Pathanamthitta: [
      'Tiruvalla',
      'Pathanamthitta Town',
      'Adoor',
      'Ranni',
      'Pandalam',
      'Kozhencherry',
      'Mallappally',
      'Konni',
      'Kumbanad',
      'Entire District',
    ],
    Wayanad: [
      'Kalpetta',
      'Sulthan Bathery',
      'Mananthavady',
      'Meenangadi',
      'Vythiri',
      'Panamaram',
      'Entire District',
    ],
    Idukki: [
      'Thodupuzha',
      'Kattappana',
      'Munnar',
      'Adimali',
      'Nedumkandam',
      'Peermade',
      'Kumily',
      'Vagamon',
      'Entire District',
    ],
    Kasaragod: [
      'Kasaragod Town',
      'Kanhangad',
      'Nileshwaram',
      'Uppala',
      'Cheruvathur',
      'Manjeshwar',
      'Entire District',
    ],
  },
  Maharashtra: {
    Mumbai: [
      'Andheri East',
      'Andheri West',
      'Bandra East',
      'Bandra West',
      'Borivali',
      'Dadar',
      'Kurla',
      'Chembur',
      'Colaba',
      'Malad',
      'Ghatkopar',
      'Powai',
      'Worli',
      'Juhu',
      'Santacruz',
      'Goregaon',
      'Kandivali',
      'Mulund',
      'Sion',
      'Lower Parel',
      'Vile Parle',
      'Mahim',
      'Entire City',
    ],
    Pune: [
      'Kothrud',
      'Hinjewadi',
      'Viman Nagar',
      'Baner',
      'Hadapsar',
      'Wakad',
      'Aundh',
      'Shivajinagar',
      'Pimpri-Chinchwad',
      'Magarpatta',
      'Bavdhan',
      'Pashan',
      'Katraj',
      'Camp',
      'Deccan Gymkhana',
      'Kalyani Nagar',
      'Entire City',
    ],
    Thane: [
      'Thane West',
      'Thane East',
      'Kalyan',
      'Dombivli',
      'Mira Road',
      'Bhayandar',
      'Ulhasnagar',
      'Bhiwandi',
      'Mumbra',
      'Badlapur',
      'Ambernath',
      'Entire City',
    ],
    'Navi Mumbai': [
      'Vashi',
      'Nerul',
      'Kharghar',
      'Belapur',
      'Panvel',
      'Airoli',
      'Ghansoli',
      'Seawoods',
      'Ulwe',
      'Kamothe',
      'Koparkhairane',
      'Entire City',
    ],
    Nagpur: ['Dharampeth', 'Sitabuldi', 'Sadar', 'Manewada', 'Wardha Road', 'Mankapur', 'Entire City'],
    Nashik: ['Panchavati', 'College Road', 'Satpur', 'Indira Nagar', 'CIDCO Nashik', 'Ambad', 'Entire City'],
    'Aurangabad (Chhatrapati Sambhajinagar)': ['CIDCO', 'Garkheda', 'Kranti Chowk', 'Waluj', 'Entire City'],
    Kolhapur: ['Rajarampuri', 'Tarabai Park', 'Shahupuri', 'Entire City'],
    Solapur: ['Civil Lines', 'Navi Peth', 'Entire City'],
    Satara: ['Powai Naka', 'Satara City', 'Karad', 'Entire District'],
    Ratnagiri: ['Ratnagiri Town', 'Chiplun', 'Entire District'],
  },
  Delhi: {
    'New Delhi': ['Connaught Place', 'Chanakyapuri', 'Vasant Kunj', 'Lajpat Nagar', 'Khan Market', 'Entire Area'],
    'South Delhi': ['Saket', 'Hauz Khas', 'Greater Kailash', 'Malviya Nagar', 'Nehru Place', 'RK Puram', 'Green Park', 'Entire Area'],
    'North Delhi': ['Model Town', 'Civil Lines', 'Pitampura', 'Rohini', 'Kashmere Gate', 'Entire Area'],
    'West Delhi': ['Janakpuri', 'Rajouri Garden', 'Dwarka', 'Tilak Nagar', 'Paschim Vihar', 'Punjabi Bagh', 'Entire Area'],
    'East Delhi': ['Preet Vihar', 'Mayur Vihar', 'Laxmi Nagar', 'Shahdara', 'IP Extension', 'Entire Area'],
    'Central Delhi': ['Karol Bagh', 'Paharganj', 'Daryaganj', 'Chandni Chowk', 'Entire Area'],
  },
  Karnataka: {
    'Bengaluru Urban': [
      'Koramangala',
      'Indiranagar',
      'Whitefield',
      'HSR Layout',
      'Electronic City',
      'Jayanagar',
      'Marathahalli',
      'Yelahanka',
      'BTM Layout',
      'JP Nagar',
      'Banashankari',
      'Hebbal',
      'Malleshwaram',
      'Rajajinagar',
      'Bellandur',
      'Sarjapur',
      'Kalyan Nagar',
      'KR Puram',
      'Entire City',
    ],
    Mysuru: ['Gokulam', 'Vijayanagar', 'Kuwempunagar', 'Jayalakshmipuram', 'VV Mohalla', 'Entire City'],
    'Dakshina Kannada (Mangaluru)': ['Mangaluru City', 'Surathkal', 'Bantwal', 'Puttur', 'Moodabidri', 'Entire District'],
    'Hubballi-Dharwad': ['Hubballi Central', 'Dharwad Town', 'Vidyanagar', 'Entire Area'],
    Belagavi: ['Tilakwadi', 'Camp', 'Khanapur', 'Entire City'],
    Udupi: ['Manipal', 'Udupi Town', 'Kundapura', 'Karkala', 'Entire District'],
  },
  'Tamil Nadu': {
    Chennai: [
      'Anna Nagar',
      'T. Nagar',
      'Adyar',
      'Velachery',
      'Tambaram',
      'OMR',
      'Porur',
      'Mylapore',
      'Chromepet',
      'Guindy',
      'Nungambakkam',
      'Vadapalani',
      'Sholinganallur',
      'Perambur',
      'Egmore',
      'Entire City',
    ],
    Coimbatore: ['RS Puram', 'Gandhipuram', 'Peelamedu', 'Saravanampatti', 'Singanallur', 'Entire City'],
    Madurai: ['KK Nagar', 'Anna Nagar', 'SS Colony', 'Tiruparankundram', 'Entire City'],
    Tiruchirappalli: ['Thillai Nagar', 'Srirangam', 'Cantonment', 'KK Nagar Trichy', 'Entire City'],
    Salem: ['Fairlands', 'Hasthampatti', 'Suramangalam', 'Entire City'],
    Tiruppur: ['Avinashi Road', 'Tiruppur Town', 'Entire City'],
  },
  Telangana: {
    Hyderabad: [
      'Banjara Hills',
      'Jubilee Hills',
      'Gachibowli',
      'HITECH City',
      'Madhapur',
      'Secunderabad',
      'Kukatpally',
      'Kondapur',
      'Begumpet',
      'Ameerpet',
      'Miyapur',
      'LB Nagar',
      'Uppal',
      'Mehdipatnam',
      'Tolichowki',
      'Entire City',
    ],
    Rangareddy: ['Cyberabad', 'Manikonda', 'Shamshabad', 'Narsingi', 'Gandipet', 'Entire District'],
    'Medchal-Malkajgiri': ['Malkajgiri', 'Kompally', 'Uppal', 'Alwal', 'Entire District'],
  },
  Gujarat: {
    Ahmedabad: ['Navrangpura', 'Satellite', 'SG Highway', 'Bodakdev', 'Maninagar', 'Prahlad Nagar', 'Vastrapur', 'Bopal', 'Ghatlodia', 'Entire City'],
    Surat: ['Adajan', 'Varachha', 'Vesu', 'Piplod', 'Ghopad Road', 'Entire City'],
    Vadodara: ['Alkapuri', 'Gotri', 'Fatehgunj', 'Manjalpur', 'Entire City'],
    Rajkot: ['Kalawad Road', 'Race Course', '150 Feet Ring Road', 'Entire City'],
  },
  'West Bengal': {
    Kolkata: ['Salt Lake', 'New Town', 'Ballygunge', 'Park Street', 'Alipore', 'Dum Dum', 'Howrah', 'Tollygunge', 'Jadavpur', 'Behala', 'Entire City'],
    Howrah: ['Shibpur', 'Bally', 'Salkia', 'Liluah', 'Entire District'],
    Darjeeling: ['Siliguri City', 'Darjeeling Town', 'Kurseong', 'Entire District'],
  },
  'Uttar Pradesh': {
    'Gautam Buddha Nagar (Noida)': ['Noida Sector 18', 'Noida Sector 62', 'Noida Sector 137', 'Greater Noida', 'Noida Extension', 'Entire Area'],
    Ghaziabad: ['Indirapuram', 'Vaishali', 'Raj Nagar', 'Crossings Republik', 'Vasundhara', 'Entire Area'],
    Lucknow: ['Gomti Nagar', 'Hazratganj', 'Aliganj', 'Indira Nagar', 'Mahanagar', 'Jankipuram', 'Entire City'],
    Kanpur: ['Civil Lines', 'Swaroop Nagar', 'Kidwai Nagar', 'Kakadeo', 'Entire City'],
    Varanasi: ['Lanka', 'Sigra', 'Cantonment', 'Godowlia', 'Entire City'],
    Agra: ['Tajganj', 'Sanjay Place', 'Dayalbagh', 'Entire City'],
  },
  Rajasthan: {
    Jaipur: ['Malviya Nagar', 'Vaishali Nagar', 'C-Scheme', 'Raja Park', 'Mansarovar', 'Jagatpura', 'Entire City'],
    Jodhpur: ['Sardarpura', 'Shastri Nagar', 'Ratanada', 'Entire City'],
    Udaipur: ['Panchwati', 'Hiran Magri', 'Fatehpura', 'Entire City'],
  },
  Punjab: {
    Ludhiana: ['Model Town', 'Sarabha Nagar', 'BRS Nagar', 'Civil Lines', 'Entire City'],
    Amritsar: ['Ranjit Avenue', 'Mall Road', 'GT Road', 'Entire City'],
    'SAS Nagar (Mohali)': ['Phase 7', 'Phase 3B2', 'Sector 70', 'Sector 82', 'Entire Area'],
  },
  Haryana: {
    Gurugram: ['DLF Phase 1-5', 'Golf Course Road', 'Sohna Road', 'Sector 56', 'Cyber City', 'Golf Course Ext Road', 'Entire City'],
    Faridabad: ['Sector 15', 'Sector 21', 'NIT Faridabad', 'Greater Faridabad', 'Entire City'],
    Panipat: ['Model Town', 'GT Road', 'Industrial Area', 'Entire City'],
  },
  'Andhra Pradesh': {
    Visakhapatnam: ['Dwaraka Nagar', 'Gajuwaka', 'MVP Colony', 'Siripuram', 'Rushikonda', 'Entire City'],
    Vijayawada: ['MG Road', 'Benz Circle', 'Governorpet', 'Satyanarayanapuram', 'Entire City'],
    Guntur: ['Broadpet', 'Arundelpet', 'Laxmipuram', 'Entire City'],
    Tirupati: ['KT Road', 'Tirumala Bypass', 'MR Palle', 'Entire City'],
  },
  'Madhya Pradesh': {
    Indore: ['Vijay Nagar', 'Palasia', 'Saket Nagar', 'Bhawarkua', 'AB Road', 'Entire City'],
    Bhopal: ['MP Nagar', 'Arera Colony', 'Kolar Road', 'New Market', 'Entire City'],
    Jabalpur: ['Civil Lines', 'Wright Town', 'Vijay Nagar', 'Entire City'],
  },
  Bihar: {
    Patna: ['Boring Road', 'Kankarbagh', 'Bailey Road', 'Patliputra Colony', 'Rajendra Nagar', 'Entire City'],
    Gaya: ['Civil Lines', 'AP Colony', 'Entire City'],
    Bhagalpur: ['Tilka Manjhi', 'Zero Mile', 'Entire City'],
  },
  Odisha: {
    Bhubaneswar: ['Saheed Nagar', 'Nayapalli', 'Jaydev Vihar', 'Patia', 'Khandagiri', 'Entire City'],
    Cuttack: ['Badambadi', 'Cantonment Road', 'CDA Sector', 'Entire City'],
  },
  Goa: {
    'North Goa': ['Panaji', 'Mapusa', 'Calangute', 'Candolim', 'Porvorim', 'Baga', 'Entire District'],
    'South Goa': ['Margao', 'Vasco da Gama', 'Ponda', 'Colva', 'Entire District'],
  },
  Assam: {
    Kamrup: ['Guwahati City', 'GS Road', 'Dispur', 'Zoo Road', 'Chandmari', 'Paltan Bazaar', 'Entire District'],
  },
  'Other / Custom': {},
};

export const INDIAN_STATES_AND_DISTRICTS = Object.keys(INDIAN_LOCATION_DATA).reduce((acc, state) => {
  acc[state] = Object.keys(INDIAN_LOCATION_DATA[state]);
  return acc;
}, {});

export const getStates = () => Object.keys(INDIAN_LOCATION_DATA);

export const getDistricts = (state) => {
  if (!state || !INDIAN_LOCATION_DATA[state]) return [];
  return Object.keys(INDIAN_LOCATION_DATA[state]);
};

export const getCities = (state, district) => {
  if (!state || !district || !INDIAN_LOCATION_DATA[state] || !INDIAN_LOCATION_DATA[state][district]) return [];
  return INDIAN_LOCATION_DATA[state][district];
};
